In [32]:
# Importing numpy
import numpy as np

-- --
1° Task

- Create a list with the names of every planet in the solar system (in order)
- Have Python tell you how many planets there are by examining your list
- Print the first four planets in the solar system (the rocky planets)
- Print the planet if it has an s at the end in its name

In [5]:
# Creating a list with the planets
planet_list = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]

In [6]:
# Planet list length
len(planet_list)

8

In [7]:
# Printing the first 4 planets
planet_list[:4]

['Mercury', 'Venus', 'Earth', 'Mars']

In [20]:
# Printing planets ending in "s"
print([  planet_list[i] for i in range(0,8) if planet_list[i][-1] == "s"  ])

['Venus', 'Mars', 'Uranus']


-- --
2° Task

A colleague from the United States shared with us the following temperature measurement, given in Fahrenheit: 30.3 [°F]

Requirements:
- Assign the received data to a variable.
- Apply the unit transformation using this variable.
- Save the data in Celsius in another variable.
- Use the print function to display both results.

In [21]:
# Assigning the data to a variable
temperature_fahrenheit = 30.3

In [22]:
# Applying the unit transformation
temperature_celsius = (5/9)*(temperature_fahrenheit - 32)

In [30]:
# Printing both results
print("Temperature values:\n" + 
      "Fahrenheit: " + str(temperature_fahrenheit) + " [°F]\n" +
      "Celsius: "    + str(round(temperature_celsius,1))    + " [°C]")

Temperature values:
Fahrenheit: 30.3 [°F]
Celsius: -0.9 [°C]


-- --
3° Task

Given the array: ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]), investigate the numpy library documentation for reshape the array to be 4x4.

In [33]:
# Reshaping the array
given_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
np.reshape(given_array, (4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

-- --
4° Task

NumPy allows us to apply mathematical functions.

Calculate the sine and cosine of the angles 0, 30, 45, 60 and 90 given in degrees:

- Create an array with the angles in degrees.
- Convert the angles to radians.
- Calculate the sine and cosine of these angles and store them in two different arrays.

In [40]:
# Storing the angles
angles_degrees = np.array([0, 30, 45, 60, 90])
print(angles_degrees)

[ 0 30 45 60 90]


In [39]:
# Converting angles to radians
angles_radians = np.radians(angles_degrees)
print(angles_radians)

[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [51]:
# Calculating sin and cos
sin_angles = np.sin(angles_radians)
print("Sin: " + str(np.round(sin_angles,3)))

cos_angles = np.cos(angles_radians)
print("Cos: " + str(np.round(cos_angles,3)))

Sin: [0.    0.5   0.707 0.866 1.   ]
Cos: [1.    0.866 0.707 0.5   0.   ]


-- --
5° Task

Finite differences | Diferencias finitas

A common approximation for computing derivatives of functions is a finite difference approximation.

This operation can be accomplished using index, slice and vectorized algebraic operations. Try to solve it for the quadratic function!

Now, read the numpy documentation to find a function to calculate.

In [67]:
# Creating a vector for x-values (spaced by 0.1)
x_values = np.linspace(0, 10, 101)
print(x_values)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [65]:
# Calculating y-values using a quadratic function: y(x)=x^2
y_values = x_values**2
print(y_values)

[0.000e+00 1.000e-02 4.000e-02 9.000e-02 1.600e-01 2.500e-01 3.600e-01
 4.900e-01 6.400e-01 8.100e-01 1.000e+00 1.210e+00 1.440e+00 1.690e+00
 1.960e+00 2.250e+00 2.560e+00 2.890e+00 3.240e+00 3.610e+00 4.000e+00
 4.410e+00 4.840e+00 5.290e+00 5.760e+00 6.250e+00 6.760e+00 7.290e+00
 7.840e+00 8.410e+00 9.000e+00 9.610e+00 1.024e+01 1.089e+01 1.156e+01
 1.225e+01 1.296e+01 1.369e+01 1.444e+01 1.521e+01 1.600e+01 1.681e+01
 1.764e+01 1.849e+01 1.936e+01 2.025e+01 2.116e+01 2.209e+01 2.304e+01
 2.401e+01 2.500e+01 2.601e+01 2.704e+01 2.809e+01 2.916e+01 3.025e+01
 3.136e+01 3.249e+01 3.364e+01 3.481e+01 3.600e+01 3.721e+01 3.844e+01
 3.969e+01 4.096e+01 4.225e+01 4.356e+01 4.489e+01 4.624e+01 4.761e+01
 4.900e+01 5.041e+01 5.184e+01 5.329e+01 5.476e+01 5.625e+01 5.776e+01
 5.929e+01 6.084e+01 6.241e+01 6.400e+01 6.561e+01 6.724e+01 6.889e+01
 7.056e+01 7.225e+01 7.396e+01 7.569e+01 7.744e+01 7.921e+01 8.100e+01
 8.281e+01 8.464e+01 8.649e+01 8.836e+01 9.025e+01 9.216e+01 9.409e+01
 9.604

In [66]:
# Approximating the derivative as: dy/dx = [y(i+1) - y(i)] / [x(i+1) - x(i)] 
dy_values = (y_values[1:] - y_values[0:-1]) / (x_values[1:] - x_values[0:-1])
print(dy_values)

[ 0.1  0.3  0.5  0.7  0.9  1.1  1.3  1.5  1.7  1.9  2.1  2.3  2.5  2.7
  2.9  3.1  3.3  3.5  3.7  3.9  4.1  4.3  4.5  4.7  4.9  5.1  5.3  5.5
  5.7  5.9  6.1  6.3  6.5  6.7  6.9  7.1  7.3  7.5  7.7  7.9  8.1  8.3
  8.5  8.7  8.9  9.1  9.3  9.5  9.7  9.9 10.1 10.3 10.5 10.7 10.9 11.1
 11.3 11.5 11.7 11.9 12.1 12.3 12.5 12.7 12.9 13.1 13.3 13.5 13.7 13.9
 14.1 14.3 14.5 14.7 14.9 15.1 15.3 15.5 15.7 15.9 16.1 16.3 16.5 16.7
 16.9 17.1 17.3 17.5 17.7 17.9 18.1 18.3 18.5 18.7 18.9 19.1 19.3 19.5
 19.7 19.9]
